### PR TITLE
Splash Screen

### LINKED ISSUE #1: Splash Screen
Will like to work on the splash Screen of Flutter App
@xlogix

### PR DESCRIPTION
**Pull request by Yashank18**
Fixes #1

### CODE REVIEW

**Comment by xlogix** [comment]
Merged! Thanks

**Comment by xlogix** [comment]
Please put all the files directly on the repo instead of putting it in the folder 'footstep'

**Comment by Yashank18** [comment]
Okay @xlogix

**Comment by xlogix** [comment]
Also, what is the package name of this app?

**Comment by Yashank18** [comment]
Keeping the package name as com.fnplus.footstep

**Comment by xlogix** [comment]
Can you keep it as tech.fnplus.footsteps?
Also, make sure to use the latest STABLE release of Flutter and updated libraries.

**Comment by Yashank18** [comment]
Yes sure.

**Pull request merged**
