### PR TITLE
Added Login Page

### LINKED ISSUE #5: Login Page UI
I would like to create UI for the login page for the fluter application.
@xlogix

### PR DESCRIPTION
**Pull request by Yashank18**
Fixes #5 
@xlogix

### CODE REVIEW

**Review by xlogix — APPROVED** [review]

**Comment by xlogix** [comment]
Can you add a screenshot of the page you created? Also, is it linked to the UI?

**Comment by Yashank18** [comment]
It's not connected yet. Yes I can add screenshot of the page. Will add the screenshot of the page asap.

**Comment by xlogix** [comment]
I tried running it but saw that the UI isn't using the color green in the app. A couple of suggestions: 

1) 'Forget your password?' opacity needs to be improved... It can be whiter & that should improve on its visibility.
2) The text "Login" can be replaced by "Welcome Back" or something welcoming.
3) Look at this for tips: https://uxplanet.org/18-ux-design-tips-for-registration-and-login-forms-f897557358ba
4) We want to encourage social logins on the screen but this UI, unfortunately, does the opposite.

**Comment by xlogix** [comment]
If you'll complete the 'forgot your password' & sign-up screen too, you'll get 7 points i.e a medium label on the pull request.

**Comment by Yashank18** [comment]
Yes sure. I will do the changes on login page. And yes will add sign up page and forgot your password page as well.

**Comment by Yashank18** [comment]
Updated and Added All the requested Pages
WhatsApp Image 2020-03-14 at 12 14 29 AM (1)
WhatsApp Image 2020-03-14 at 12 14 29 AM (2)
WhatsApp Image 2020-03-14 at 12 14 29 AM (3)
WhatsApp Image 2020-03-14 at 12 14 29 AM

**Comment by Yashank18** [comment]
@xlogix Please Check

**Comment by xlogix** [comment]
Looks good!

**Comment by Yashank18** [comment]
Sir please change the label as well

**Comment by xlogix** [comment]
Done!

**Pull request merged**
