### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kuljeet-123**
Fixes Issue: #9 

Changes: 

Updated the documentation of the project.

### CODE REVIEW

**Comment by Kuljeet-123** [comment]
@xlogix Please review it I have added the installation process and instruction for the google_service file.

**Comment by xlogix** [comment]
Why did you add cloud firestore?

**Comment by Kuljeet-123** [comment]
@xlogix Do I have to remove all the firestore installation from the file...or just something else.

**Comment by xlogix** [comment]
Just removing firestore is fine. Core and auth are being used!

**Comment by xlogix** [comment]
@Kuljeet-123 I don't want people to create their own Firebase project but instead (just like the main repo of webapp) you can just ask them to fill a form to request access to the test firebase app we're using. That way they can add the SHA-1 fingerprint and download the new google services file...

**Comment by Kuljeet-123** [comment]
@xlogix I have updated the code please review it and let me know if some correction is needed.

**Review by xlogix — APPROVED** [review]

**Pull request merged**
