### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kuljeet-123**
Fixes issue:#9.

Changes:
Updated the README of the project.

### CODE REVIEW

**Comment by Kuljeet-123** [comment]
@xlogix I have updated the code.Please review it.

**Comment by xlogix** [comment]
Can you update the readme according to the new format in the main repo?

**Comment by xlogix** [comment]
Also, ping me on Slack for details on app description.

**Comment by Kuljeet-123** [comment]
@xlogix I just pinged you to slack for description...

**Comment by Kuljeet-123** [comment]
@xlogix Please review my PR and let me know if correction is required.

**Review by xlogix — APPROVED** [review]

**Comment by xlogix** [comment]
Although it doesn't anything related to the UI

**Comment by xlogix** [comment]
Add instructions for running the app on Android and iOS

**Comment by Kuljeet-123** [comment]
@xlogix I have already provided the installation process for android and ios...what else more I have to write??

**Comment by xlogix** [comment]
Add instruction to make sure flutter is installed.
Check path, flutter doctor, flutter run. Also we need to add instructions to add the google_services file.

**Comment by xlogix** [comment]
@Kuljeet-123 How is it coming?

**Comment by Kuljeet-123** [comment]
@xlogix I am working on this....I'll raise the PR by tomorrow morning definitely

**Comment by xlogix** [comment]
I'll merge this PR and you can raise another one tomorrow morning with thee updates :)

**Comment by Kuljeet-123** [comment]
@xlogix  I have  raised the PR #18 .Please review it.

**Pull request merged**
